config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  get '/login', :to => 'users#new', as:'login'
  post '/login', :to => 'sessions#create'
  get '/logout' => 'sessions#destroy', as:'logout'
  post '/sessions/new' =>'sessions#create', as: 'new_session'
  
  get 'pages/index', as:'pages_index'
  get 'pages/new', as:'new_page'
  post 'pages/create' =>'pages#create', as:'create_page'
  get 'pages/:id' => 'pages#show', as:'show_page'
  get 'pages/:id/edit' =>'pages#edit', as:'edit_page'
  post 'pages/:id/edit' => 'pages#update', as:'update_page'
  get 'pages/:id/delete' => 'pages#confirmdelete', as:'confirm_delete_page'
  post 'pages/:id/delete' => 'pages#destroy', as:'delete_page'
  get 'pages/', :to => 'pages#index'

  get 'users/:id' => 'users#show', as: 'show_user'
  get 'users/:id/edit' => 'users#edit', as: 'edit_user'
  post 'users/create' => 'users#create', as: 'create_user'

  get 'blocks/new' => 'blocks#new', as:'new_block'
  post 'blocks/create' => 'blocks#create', as:'create_block'
  get 'blocks/:id' => 'blocks#show', as:'show_block'
  get 'blocks/:id/edit' => 'blocks#edit', as:'edit_block'
  post 'blocks/:id/edit' => 'blocks#update', as:'update_block'
  get 'blocks/:id/delete' => 'blocks#confirmdelete', as:'confirm_delete_block'
  post 'blocks/:id/delete' => 'blocks#destroy', as:'delete_block'
  delete 'comments/delete' => 'blocks#destroycomment', as:'delete_comment'

  post 'comments/create' => 'blocks#createcomment', as:'create_comment'

end

app/models/block.rb
class Block < ActiveRecord::Base
  belongs_to :user
  validates :description, :name, presence:true
  has_many:comments
  has_many:pages, through: :displays
  has_many:displays

end

app/models/clan.rb
class Clan < ActiveRecord::Base
    has_many:users
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  validates :body, presence:true
  belongs_to :block

end

app/models/display.rb
class Display < ActiveRecord::Base
  belongs_to :page
  belongs_to :block
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :user
  has_many:displays
  has_many:blocks, through: :displays
  validates :description, :name, presence:true

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :clan
  has_secure_password
  has_many:blocks
  has_many:comments
  has_many:pages
  validates :name, :email, presence:true
  validates :email, uniqueness:true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
    if session[:user_id]
      return User.find(session[:user_id]) 
    else
      return nil
    end
  end
  helper_method :current_user
  # before_action :verify_user
  private
  def verify_user
    if current_user
      return self
    else
      redirect_to login_path and return
    end
  end
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  def new
    @pages=Page.all
    if params[:format]
      @page=Page.find(params[:format])
    else
      @page=nil
    end
  end

  def show
    @block=Block.find(params['id'])
    @comments=@block.comments.includes(:user)
  end

  def edit
    @block=Block.find(params['id'])
    @comments=@block.comments
    @pages=Page.all
    @selectedpages=@block.pages
  end
  
  def update
    @block=Block.find(params[:id])
    if @block.user==current_user
      @block.update(params.require(:block).permit(:name, :kind, :description, :body))
      p params
      x=(@block.pages.ids).map! { |i| i.to_i }
      y=params[:block]['page_id'].map! { |i| i.to_i }
      z= x & y
      secondx=x-z
      secondy=y-z
      secondx.each do |i|
        Display.where("block_id = ? AND page_id = ?",@block.id, i).take.delete
      end
      secondy.each do |i|
        Display.create(block:@block,page:Page.find(i))
      end
    end
    redirect_to show_block_path(@block) and return
  end

  def create
    @block = Block.new(params.require(:block).permit(:name, :kind, :description, :body))
    @block.user=current_user
    if @block.save
      params[:block]['page_id'].each do |i|
        Display.create(block:@block,page:Page.find(i))
      end
      @block=Block.last
      redirect_to pages_index_path and return
    else
      flash[:notice] = @block.errors.messages
      redirect_to new_block_path and return
    end
  end

  def confirmdelete
    @block=Block.find(params['id'])
    redirect_to pages_index_path and return if @block.user!=current_user
  end

  def destroy
    @block=Block.find(params['id'])
    if @block.user==current_user
      @block.delete
      redirect_to pages_index_path
    else
      redirect_to show_block_path(@block)
    end
  end

  def createcomment
    session[:return_to] = request.referer
    @comment =Comment.new(params.require(:comment).permit(:body))
    @block=Block.find(params[:comment]['block_id'])
    @comment.block=@block
    @comment.user=current_user if current_user.id.to_s==params[:comment]['user_id']
    @comment.save
    flash[:notice] = @comment.errors.messages
    redirect_to session.delete(:return_to)
  end

  def destroycomment
    session[:return_to] = request.referer
    @comment=Comment.find(params[:comment]['id'])
    if @comment.user==current_user
      @comment.delete
      redirect_to session.delete(:return_to)
    else
      redirect_to session.delete(:return_to)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages=Page.all.includes(:blocks)
    @user=current_user
  end

  def show
    @user=current_user
    @page=Page.find(params[:id])
    @blocks=@page.blocks.includes(:comments)
  end

  def new
    @user=current_user
  end
  def create
    @user=current_user
    @page = Page.new(page_params)
    @page.user=@user
    @page.save
    if @page.errors.messages
      flash[:notice] = @page.errors.messages
      redirect_to pages_index_path and return
    else
      redirect_to show_page_path(@page) and return
    end
  end

  def edit
    @page=Page.find(params[:id])
  end
  
  def update
    @page=Page.find(params[:id])
    if @page.user==current_user
      @page.update(page_params)
    end
    redirect_to show_page_path(@page) and return
  end
  
  def confirmdelete
    @page=Page.find(params['id'])
    redirect_to pages_index_path and return if @page.user!=current_user
  end

  def destroy
    @page=Page.find(params['id'])
    if @page.user==current_user
      @page.delete
      redirect_to pages_index_path and return
    else
      redirect_to show_page_path(@page)
    end
  end


  private
  def page_params
    params.require(:page).permit(:name, :description,)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def createomniauth
    auth_hash = request.env['omniauth.auth']
    render :text => auth_hash.inspect
  end
  def new
    if session[:user_id] 
      redirect_to pages_index_path and return
    end
  end
  def create
    @user=User.find_by email:params['email']
    unless @user
        flash['passworderror'] = "Email was not found in database"
        redirect_to login_path and return
    end
    if @user.authenticate(params['password'])
        session[:user_id]=@user.id
        redirect_to pages_index_path(@user.id) and return
    else
        flash['passworderror'] = "Invalid"
        redirect_to login_path and return
    end
  end
  def destroy
    session[:user_id]=nil
    redirect_to login_path and return
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if current_user
      redirect_to pages_index_path and return
    end
    @clans=Clan.all
    render :layout => false
  end

  def create
    @user = User.new(params.require(:user).permit(:name, :email, :password))
    @user.clan=Clan.find(params[:user]['clan'])
    if @user.save
      session[:user_id]=User.last.id
      redirect_to pages_index_path and return
    else
      flash[:notice] = @user.errors.messages
      redirect_to login_path and return
    end
  end
  
  def show
    redirect_to show_user_path(current_user) and return if params['id']!=current_user.id.to_s
    @user = current_user
    @pages = @user.pages
    @blocks =@user.blocks
  end
  
  def edit
    redirect_to edit_user_path(current_user) and return if params['id']!=current_user.id.to_s
    @user = current_user
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blocks/confirmdelete.html.erb
<h1>Are you sure you want to delete <%= @block.name %> and all of its comments? This action cannot be undone</h1>
<form method='post' action:''>
<input type = 'hidden' name = "authenticity_token" value = "<%=form_authenticity_token%>">
<input type='submit' value='YES'>
<%= button_to "NO", show_block_path(@block), :method => "get" %>

app/views/blocks/edit.html.erb
<!DOCTYPE html>
<html>
<head>
<script src='https://cloud.tinymce.com/stable/tinymce.min.js'></script>
<script>
tinymce.init({
  selector: '#mytextarea',
  plugins:"textcolor lists",
  height: 300,
  toolbar: 'bold italic underline forecolor backcolor  bullist numlist alignleft aligncenter alignright alignjustify',
  browser_spellcheck: true
});
</script>
</head>

<body>
<h1>Edit <%= @block.name %></h1>
<p class='text-warning'><em>if full editor does not appear below, please reload page</em></p>
<form action='' method='post'>
<input type = 'hidden' name = "authenticity_token" value = "<%=form_authenticity_token%>">
<input type = 'hidden' name ="block[user_id]" value ='<%= current_user.id %>'>
Title: <input type = 'text' name ="block[name]" value='<%= @block.name %>'>
Description: <input type = 'text' name ="block[description]" value='<%= @block.description %>'>
Type of Content <select name="block[kind]">
<option value='Recipe'>Recipe</option>
<option value='Note'>Note</option>
<option value='Timeline'>Timeline</option>
</select>
<label>Include this content on pages: </label>
<select multiple name='block[page_id][]'>
  <% @pages.each do |page| %>
    <% if @selectedpages.include? page %>
    <option selected value='<%= page.id %>'><%= page.name %></option>
    <% else %>
    <option value='<%= page.id %>'><%= page.name %></option>
    <% end %>
  <% end %>
</select>
<textarea id="mytextarea" name='block[body]'><%= sanitize @block.body %></textarea>
<input type ='submit' value="Update">
</form>
</body>
</html>

app/views/blocks/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <script src='https://cloud.tinymce.com/stable/tinymce.min.js'></script>
  <script>
  tinymce.init({
    selector: '#mytextarea',
    plugins:"textcolor lists link",
    height: 300,
    toolbar: 'bold italic underline forecolor backcolor  bullist numlist link',
    browser_spellcheck: true
  });
  </script>
</head>

<body>
<h1>Add Content</h1>
<p class='text-warning'><em>if full editor does not appear below, please reload page</em></p>
<form action="<%= create_block_path %>" method='post'>
<input type = 'hidden' name = "authenticity_token" value = "<%=form_authenticity_token%>">
<input type = 'hidden' name ="block[user_id]" value ='<%= current_user.id %>'>
Title: <input type = 'text' name ="block[name]">
Description: <input type = 'text' name ="block[description]">
Type of Content <select name="block[kind]">
<option value='Recipe'>Recipe</option>
<option value='Note'>Note</option>
<option value='Timeline'>Timeline</option>
<option value='Info'>Info</option>
<option value='Other'>Other</option>
</select>
<label>Include this content on pages: </label>
<select multiple name='block[page_id][]'>
  <% @pages.each do |page| %>
    <% if page==@page %>
    <option selected value='<%= page.id %>'><%= page.name %></option>
    <% else %>
    <option value='<%= page.id %>'><%= page.name %></option>
    <% end %>
  <% end %>
</select>
<br>
<textarea id="mytextarea" name='block[body]'></textarea>
<input type ='submit' class='btn btn-primary' value="Add Content">
</form>
</body>
</html>

app/views/blocks/show.html.erb
<div class='row'>
    <div class='col-9'>
        <div class='card border-primary'>
            <h1 class='card-header'><%= @block.name %></h1>
            <h3 class='card-header'><%= @block.kind %>, written by <%= @block.user.name %></h3>
            <p class='card-body'>Description: <%= @block.description %><p>
            <div class='card-body'><%= (sanitize @block.body) %></div>
            <% if (@block.user==current_user) %>
            <p class='card-footer'><%= link_to 'Edit Content', edit_block_path(@block), :class =>'text-danger' %>  |
            <%= link_to 'Delete Content', confirm_delete_block_path(@block), :class =>'text-danger' %></p>
        <% end %>
                </div>
        <p class='text-secondary'><em>This is included on: <% @block.pages.each do |page| %><%= link_to page.name, show_page_path(page) %>, <% end %></em></p>
    </div>
    <div class='col-3'>
        <% if (@comments!= []) %>
            <% @comments.each do |comment| %>
                <div class='card border-primary mb-3'>
                    <p class='text-muted card-header'><%= (comment.created_at).strftime("%m/%d/%Y") %>: <%= comment.user.name %> said</p>
                    <p class='card-body'><%= comment.body %></p>
                    <% if (comment.user==current_user) %>
                        <form method='post' action="<%= delete_comment_path %>">
                            <input type = 'hidden' name = "authenticity_token" value = "<%=form_authenticity_token%>">
                            <input type = 'hidden' name ='_method' value='DELETE'>
                            <input type = 'hidden' name ='comment[id]' value='<%= comment.id %>'>
                            <input class='btn btn-danger' type='submit' value='Delete'>
                        </form>
                    <% end %>
                </div>
            <% end %>
        <% end %>
        <form action="<%= create_comment_path %>" method='post'>
            <input type = 'hidden' name = "authenticity_token" value = "<%=form_authenticity_token%>">
            <input type = 'hidden' name ="comment[user_id]" value ='<%= current_user.id %>'>
            <input type = 'hidden' name ="comment[block_id]" value ='<%= @block.id %>'>
            <textarea rows='4' cols='42' name="comment[body]"></textarea>
            <br>
            <input type ='submit' class = 'btn btn-primary' value="Comment">
        </form>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NutellaWiki</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarColor03">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= pages_index_path %>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_page_path %>">Add a page</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_block_path %>">Add content</a>
      </li>
      <% if (current_user) %>
      <li class="nav-item">
        <a class="nav-link" href="<%= show_user_path(current_user) %>">My Profile</a>
      </li>
      <% end %>
    </ul>
  </div>
</nav>
<div class='container-fluid' style='border:1pt #325D88 solid; padding:10px;'>
<%= yield %>
</div>
<footer class='footer navbar-expand-lg navbar-light bg-light'>
  <button href="<%= logout_path %>" type="button" class="btn btn-info my-2 my-sm-0">Logout</button>
</footer>
</body>
</html>

app/views/pages/confirmdelete.html.erb
<h1>Are you sure you want to delete <%= @page.name %>? This action cannot be undone</h1>
<form method='post' action:''>
<input type = 'hidden' name = "authenticity_token" value = "<%=form_authenticity_token%>">
<input type = 'hidden' name ='id' value='<%= @page.id %>'>
<input type='submit' value='YES'>
<%= button_to "NO", show_page_path(@page), :method => "get" %>

app/views/pages/edit.html.erb
<h3>Edit Page</h3>
<form class='form' action='' method='post'>
<input type = 'hidden' name = "authenticity_token" value = "<%=form_authenticity_token%>">
<input type = 'hidden' name ="page[user_id]" value ='<%= current_user.id %>'>
Page Name: <input type = 'text' name ="page[name]" value='<%= @page.name %>'>
Description: <input type ='text' name ="page[description]" value='<%= @page.description %>'>
<input class='btn btn-primary' type ='submit' value="UPDATE">
</form>

app/views/pages/index.html.erb
<h1>The <%= @user.clan.name%> Family Wiki</h1>
<div class='row'>
    <% @pages.each do |page| %>
        <div class='col-sm-2'>
            <div class='card mb-3 border-info'>
                <h3 class='card-header'><%= link_to page.name, show_page_path(page) %></h3>
                <div class='card-body'>
                    <h5 class'card-title'><em><%= page.description %></em></h5>
                </div>
                <% unless (page.blocks==[]) %>
                <div class='card-body'>
                    <ul class='list-group list-group-flush'>
                        <% page.blocks.each do |block| %>
                        <li class='list-group-item'><%= link_to block.name, show_block_path(block) %>- <%= block.kind %></li>
                        <% end %>
                    </ul>
                </div>
                <% end %>
                <div class='card-footer'><%= link_to 'Add content to this page', new_block_path(page), :class =>'text-info' %></div>
                <% if (page.user==current_user) %>
                    <p class='card-footer'><%= link_to 'Edit Page', edit_page_path(page), :class =>'text-danger' %>  |
                    <%= link_to 'Delete Page', confirm_delete_page_path(page), :class =>'text-danger' %></p>
                <% end %>
                
            </div>
        </div>
    <% end %>
</div>

<h5>Add a new page</h5>
<form action="<%= create_path_path %>" method='post'>
<input type = 'hidden' name = "authenticity_token" value = "<%=form_authenticity_token%>">
<input type = 'hidden' name ="page[user_id]" value ='<%= @user.id %>'>
Page Name: <input type = 'text' name ="page[name]">
Description: <input type ='text' name ="page[description]">
<input type ='submit' class='btn btn-primary' value="Add">
</form>

app/views/pages/new.html.erb
<h3>Create a new Page</h3>
<form action="<%= create_pate_path %>" method='post'>
<input type = 'hidden' name = "authenticity_token" value = "<%=form_authenticity_token%>">
<input type = 'hidden' name ="page[user_id]" value ='<%= @user.id %>'>
Page Name: <input type = 'text' name ="page[name]">
Description: <input type ='text' name ="page[description]">
<input type ='submit' value="CREATE PAGE">
</form>

app/views/pages/show.html.erb
<h1><%= @page.name %></h1>
<h3><em><%= @page.description %></em></h3>
<% @blocks.each do |block| %>
    <div class='row'>
        <div class='col-9'>
            <div class='card border-primary'>
                <h2 class='card-header'><%= link_to block.name, show_block_path(block) %></h2>
                <h5 class='card-header'><%= block.kind %>, written by <%= block.user.name %></h5>
                <div class='card-body'><%= (sanitize block.body) %></div>
            </div>
        </div>
        <div class='col-3'>
            <% block.comments.each do |comment| %>
                <div class='card border-primary mb-3'>
                    <p class='text-muted card-header'><%= (comment.created_at).strftime("%m/%d/%Y") %>: <%= comment.user.name %> said</p>
                    <p class='card-body'><%= comment.body %></p>
                    <% if (comment.user==current_user) %>
                        <form method='post' action:'/wiki/comments/delete/'>
                            <input type = 'hidden' name = "authenticity_token" value = "<%=form_authenticity_token%>">
                            <input type = 'hidden' name'_method' value='DELETE'>
                            <input type = 'hidden' name ='comment[id]' value='<%= comment.id %>'>
                            <input class='btn btn-danger' type='submit' value='Delete'>
                        </form>
                    <% end %>
                </div>
            <% end %>
            <form action="<%= create_comment_path %>" method='post'>
                <input type = 'hidden' name = "authenticity_token" value = "<%=form_authenticity_token%>">
                <input type = 'hidden' name ="comment[user_id]" value ='<%= current_user.id %>'>
                <input type = 'hidden' name ="comment[block_id]" value ='<%= block.id %>'>
                <textarea rows='4' cols='42' name="comment[body]"></textarea>
                <br>
                <input type ='submit' class = 'btn btn-primary' value="Comment">
            </form>

        </div>
    </div>
<% end %>

<div class='card-footer'><%= link_to 'Add content to this page', new_block_path(@page), :class =>'text-info' %></div>
<% if (@page.user==current_user) %>
    <p class='card-footer'><%= link_to 'Edit Page', edit_page_path(@page), :class =>'text-danger' %>  |
    <%= link_to 'Delete Page', confirm_delete_page_path(@page), :class =>'text-danger' %></p>
<% end %>

app/views/users/edit.html.erb
# <form action = "/users/<%= @user.id %>/update" method = "post">
#   <input type = 'hidden' name = "authenticity_token" value = "<%=form_authenticity_token%>">
#   <label>Name</label>
#   <input type = "text" name = "user[name]" id = "user_name" value='<%= @user.name %>'>
#   <label>Clan: <%= @user.clan.name %></label>
#   <label>Email</label>
#   <input type = "text" name = "user[email]" id = "user_email" value='<%= @user.email %>'>
#   <label>Password</label>
#   <input type = "password" name = "user[password]" id = "user_password">
#   <input type = "submit" value = "Update" id='joinbutton'>
# </form>
<h1>user edit page</h1>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Welcome to the NutellaWiki</h1>
<div>
<h1>Register</h1>
<% if flash[:notice] %>
  <% flash[:notice].each do |key,value| %>
    <p id="notice"><%= key %> <%= value[0] %></p>  
  <% end %>
<% end %>
<form action = "<%= create_user_path %>" method = "post">
  <input type = 'hidden' name = "authenticity_token" value = "<%=form_authenticity_token%>">
  <label>Name</label>
  <input type = "text" name = "user[name]" id = "user_name">
  <label>Clan</label>
  <select name='user[clan]'>
    <% @clans.each do |clan| %>
    <option value='<%= clan.id %>'><%= clan.name %></option>
    <% end %>
    </select>
  <label>Email</label>
  <input type = "text" name = "user[email]" id = "user_email">
  <label>Password</label>
  <input type = "password" name = "user[password]" id = "user_password">
  <input type = "submit" value = "Register" id='joinbutton'>
</form>
</div>
<div>
<h1>Login</h1>
<% if flash[:notice] %>
  <% flash[:notice].each do |key,value| %>
    <p id="notice"><%= key %> <%= value[0] %></p>  
  <% end %>
<% end %>
<% if flash[:passworderror] %>
<p><%= flash[:passworderror] %>
<% end %>
<form action = "<%= new_session_path %>" method = "post">
  <input type = 'hidden' name = "authenticity_token" value = "<%=form_authenticity_token%>">
  <label>Email</label>
  <input type = "text" name = "email" id = "email">
  <label>Password</label>
  <input type = "password" name = "password" id = "password">
  <input type = "submit" value = "Login" name="Login" id='loginbutton'>
</form>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<h3><%= @user.email %></h3>
<br>
<h5>Owned Pages</h5>
<ul class='list-group list-group-flush'>
    <% @pages.each do |page| %>
        <li class><%= link_to page.name, show_page_path(page) %></li>
    <% end %>
</ul>
<br>
<h5>Created Content</h5>
<ul class='list-group list-group-flush'>
    <% @blocks.each do |block| %>
        <li><%= link_to block.name, show_block_path(block) %></li>
    <% end %>
</ul>
<br>
<% if (current_user==@user) %>
<p><%= link_to 'Edit Info', edit_user_path(@user), :class =>'text-danger' %></p>
<% end %>